### ISSUE TITLE
调用 delete 类 API 时报 ValueError

### ISSUE THREAD

**Issue by messense** [douban/douban-client#36]
根据豆瓣 API 文档，比如 book_v2 中删除笔记调用 client.book._delete(url) 删除成功但会报 ValueError，原因在于此 API 无返回信息，但 api/base.py 中 check_exception 装饰器在无错误的情况下总是返回 resp.parsed ，resp.parsed 中没有检查是否有返回信息便试图转换结果为 json 导致 ValueError.

**Comment by liluo** [comment]
`client.book._delete(url)` 中 `url` 的值是？

**Comment by messense** [comment]
/v2/book/annotation/xxx xxx 是笔记 id

**Comment by messense** [comment]
```
>>> entrypoint
u'/v2/book/annotation/31194303'                   
>>> client.book._delete(entrypoint)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/messense/.virtualenvs/everbean/lib/python2.7/site-packages/douban_client/api/base.py", line 16, in _check
    return resp.parsed
  File "/Users/messense/.virtualenvs/everbean/lib/python2.7/site-packages/pyoauth2/libs/response.py", line 42, in parsed
    return self.resp.json()
  File "/Users/messense/.virtualenvs/everbean/lib/python2.7/site-packages/requests/models.py", line 741, in json
    return json.loads(self.text, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 383, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by liluo** [comment]
明白了， 应该在 `resp.parsed` 之前判断一下 `resp.body` 的， 稍晚一些会修复。

**Comment by liluo** [comment]
@messense  已经修复 #37 

 clone 这个仓库重新安装一下 douban-client 吧, 暂时不会为这个 bug release 新版本.
