### ISSUE TITLE
douban_client.api.error.DoubanAPIError: ***400 (Bad Request)***

### ISSUE THREAD

**Issue by yianlai** [douban/douban-client#45]
我寫了下面簡單的code:
token = '-----------------------'
client.auth_with_token(token)

my_content = client.user.me
print my_content

然後得到下面的錯誤：
Traceback (most recent call last):
  File "test.py", line 31, in <module>
    my_content = client.user.me
  File "/usr/local/lib/python2.7/site-packages/douban_client/api/user.py", line 16, in me
    return self.get('~me')
  File "/usr/local/lib/python2.7/site-packages/douban_client/api/user.py", line 12, in get
    return self._get('/v2/user/%s' % id)
  File "/usr/local/lib/python2.7/site-packages/douban_client/api/base.py", line 15, in _check
    raise DoubanAPIError(resp)
douban_client.api.error.DoubanAPIError: **_400 (Bad Request)**_ {u'msg': u'invalid_access_token: 4b19728adfd624be', u'code': 103, u'request': u'GET /v2/user/~me'}
notebook20:Douban_API standard2$ 

能不能請Liluo指點一下

**Comment by liluo** [comment]
@yianlai 

手机回复乱码了，更新一下。

上面的错误信息，注意看其中的这部分：

```
DoubanAPIError: 400 (Bad Request) {u'msg': u'invalid_access_token: 4b19728adfd624be', u'code': 103, u'request': u'GET /v2/user/~me'}
```

传入的是 token 错误，长度也不对，正确的 `token` 是 32 位的。你传入的是授权返回的 `auth_code` 吧？（从 URL 中复制来的？）
